
name: Merge PR
on:
  # Trigger the workflow on push or pull request, 
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  log-something:
    runs-on: ubuntu-latest
    steps:
    - name: just echo a message
      run: |
        echo Hello there!   
  merge-PR:
     runs-on: ubuntu-latest
     steps:
     - name: Add Grafana annotation
       uses: frankie567/grafana-annotation-action@v1.0.2
       with:
        apiHost: https://grafana.web.tools.bbc.co.uk
        apiToken: ${{ secrets.apiKey }}
        text: test2
        dashboardId: 18
        tags: deployment,github 
      
