
name: Merge PR
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  merge-PR:
    runs-on: ubuntu-latest
    steps:
    - name: Add Grafana annotation
      uses: frankie567/grafana-annotation-action@v1.0.2
      with:
        apiHost: https://grafana.web.tools.bbc.co.uk/
        apiToken: eyJrIjoiQkhZU0dkNFA3T2Y2NjBKVkV5MkVyVXI5Q1g2VGpvUnEiLCJuIjoiZ3JhZmFuYS1hbm5vdGF0aW9uIiwiaWQiOjF9
        text: test2
        dashboardId: YBiFemjWz
        tags: deployment,github
