name: Merge PR
on:
  pull_request:
    types: [closed] 
jobs:
  merge-PR:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: frankie567/grafana-annotation-action@v1.0.2
      with:
        apiHost: https://grafana.web.tools.bbc.co.uk/
        apiToken: eyJrIjoiQkhZU0dkNFA3T2Y2NjBKVkV5MkVyVXI5Q1g2VGpvUnEiLCJuIjoiZ3JhZmFuYS1hbm5vdGF0aW9uIiwiaWQiOjF9
        text: test2
        dashboardId: YBiFemjWz
        tags: deployment,github
